name = "tvpage"
description = "starter theme tvpage"
min_version = 0.17

[[tvp-templates]]
	name = "Captivate"
	uniqueName = "captivate"
	path = "layouts/captivate"
	preview = "https://www.goodlookingbean.com/tv"
	[[tvp-templates.thumbnails]]
		desktop = "https://s3-us-west-2.amazonaws.com/tvpage-a.tvpage.com/dev/site-templates/preview/dtop_preview_captivate.png"
		mobile = "https://s3-us-west-2.amazonaws.com/tvpage-a.tvpage.com/dev/site-templates/preview/mobile_preview_captivate.png"
		tablet = "https://s3-us-west-2.amazonaws.com/tvpage-a.tvpage.com/dev/site-templates/preview/tablet_preview_captivate.png"

[[tvp-widgets]]
	name = "Carousel"
	uniqueName = "carousel"
	path = "layouts/carousel"
	preview = "http://preview.tvpage.com"
	settings = ['playback']
	description = "Carousel is our most popular widget and can be used on a variety of pages. The user is presented with a series of thumbnails. The video plays in a modal after a thumbnail is clicked."
	[[tvp-widgets.thumbnails]]
		desktop = "https://do0631budpzeh.cloudfront.net/dev/widgets/templates_preview/preview_Carousel_dtop.png"
		mobile = "https://do0631budpzeh.cloudfront.net/dev/widgets/templates_preview/preview_Carousel_mobile.png"
		tablet = "https://do0631budpzeh.cloudfront.net/dev/widgets/templates_preview/preview_Carousel_tablet.png"

#[[tvp-widgets]]
#	name = "Inline"
#	uniqueName = "inline"
#	path = "layouts/inline"
#	preview = "http://preview.tvpage.com"
#	settings = ['playback','products']
#	description = " Inline provides an engaging experience and are a great choice for presenting many videos or products within a defined space. The user can interact with the videos and the products without ever launching a modal."
#	[[tvp-widgets.thumbnails]]
#		desktop = "http://do0631budpzeh.cloudfront.net/dev/widgets/templates_preview/preview_Inline_dtop.png"
#		mobile = ""
#		tablet = ""

#[[tvp-widgets]]
#	name = "PDP"
#	uniqueName = "pdp"
#	path = "layouts/pdp"
#	preview = "http://preview.tvpage.com"
#	settings = ['playback']
#	description = "Product Detail Page (PDP) is purpose-built to that dynamically renders a video that matches an indivdual SKU. Use this widget to close the deal especially on higher-priced items."
#	[[tvp-widgets.thumbnails]]
#		desktop = "http://do0631budpzeh.cloudfront.net/dev/widgets/templates_preview/preview_PDP_dtop.png"
#		mobile = ""
#		tablet = ""

[[tvp-widgets]]
	name = "Side Bar"
	uniqueName = "sidebar"
	path = "layouts/sidebar"
	preview = "http://preview.tvpage.com"
	settings = ['playback']
	description = "Sidebar is a great compliment to a traditional 2-column or 3-column layout. The user is presented with a series of thumbnails. The video plays in a modal after a thumbnail is clicked."
	[[tvp-widgets.thumbnails]]
		desktop = "https://do0631budpzeh.cloudfront.net/dev/widgets/templates_preview/preview_SideBar_dtop.png"
		mobile = "https://do0631budpzeh.cloudfront.net/dev/widgets/templates_preview/preview_SideBar_mobile.png"
		tablet = "https://do0631budpzeh.cloudfront.net/dev/widgets/templates_preview/preview_SideBar_tablet.png"

[[tvp-widgets]]
	name = "Solo"
	uniqueName = "solo"
	path = "layouts/solo"
	preview = "http://preview.tvpage.com"
	settings = ['playback']
	description = "Solo is a simple player that works seamlessly across devices. The video plays inline."
	[[tvp-widgets.thumbnails]]
		desktop = "https://do0631budpzeh.cloudfront.net/dev/widgets/templates_preview/preview_Solo_dtop.png"
		mobile = "https://do0631budpzeh.cloudfront.net/dev/widgets/templates_preview/preview_Solo_mobile.png"
		tablet = "https://do0631budpzeh.cloudfront.net/dev/widgets/templates_preview/preview_Solo_tablet.png"
